version: '3.7'
services:
  ce-ms-psqldb:
    image: postgres:14-alpine
    container_name: ce-ms-psqldb
    restart: always
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ce-ms-db:/var/lib/postgresql/data
    ports:
      - '5430:5432'

volumes:
  ce-ms-db:
