on:
  push:
    branches:
      - dev
env:
  GH_OAUTH_TOKEN: ${{ secrets.GH_OAUTH_TOKEN }}
  GH_API_DOMAIN: ${{ secrets.GH_API_DOMAIN }}

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub.
    runs-on: ubuntu-latest
    steps:
      - name: SSH and deploy node app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo "Create `docker-compose` directory if non-existant"
            mkdir -p docker-compose/
            echo "Deploy to production environment"
            curl \
            -H 'Authorization: token ${{env.GH_OAUTH_TOKEN}}' \
            -H 'Accept: application/vnd.github.v3.raw' \
            -O \
            -L 'https://${{env.GH_API_DOMAIN}}/repos/rutaks/ce-attendance-ms-api/contents/docker-compose/dev.docker-compose.yml?ref=dev' >> docker-compose/dev.docker-compose.yml
