on:
  push:
    branches:
      - dev

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub.
    runs-on: ubuntu-latest
    steps:
      - name: SSH and deploy node app
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          GH_OAUTH_TOKEN: ${{ secrets.GH_OAUTH_TOKEN }}
          GH_API_DOMAIN: ${{ secrets.GH_API_DOMAIN }}
        uses: appleboy/ssh-action@0.1.4
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            echo "Deploy to production environment"
            curl \
            -H 'Authorization: token $GH_OAUTH_TOKEN' \
            -H 'Accept: application/vnd.github.v3.raw' \
            -O \
            -L 'https://$GH_API_DOMAIN/repos/rutaks/ce-attendance-ms-api/contents/docker-compose/dev.docker-compose.yml?ref=dev' >> docker-compose/dev.docker-compose.yml
