on:
  push:
    branches:
      - dev

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub.
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ secrets.REPO_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: SSH and deploy node app
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          GH_OAUTH_TOKEN: ${{ secrets.GH_OAUTH_TOKEN }}
          GH_API_DOMAIN: ${{ secrets.GH_API_DOMAIN }}
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_PUBLIC_SSH_KEY }}
          script: |
            echo "Deploy to production environment"
            curl \
            -H 'Authorization: token $GH_OAUTH_TOKEN' \
            -H 'Accept: application/vnd.github.v3.raw' \
            -O \
            -L 'https://$GH_API_DOMAIN/repos/rutaks/ce-attendance-ms-api/contents/docker-compose/dev.docker-compose.yml?ref=dev' >> docker-compose/dev.docker-compose.yml
