on:
  push:
    branches:
      - dev
env:
  GH_OAUTH_TOKEN: ${{ secrets.GH_OAUTH_TOKEN }}
  GH_API_DOMAIN: ${{ secrets.GH_API_DOMAIN }}
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  ENV_VARS: ${{ secrets.DEV_ENV_VARS }}
  APP_REGISTRY_NAME: rootsum/ce-ms-api

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub.
    runs-on: ubuntu-latest
    steps:
      - name: SSH and deploy node app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo "Create `docker-compose` directory if non-existant"
            mkdir -p docker-compose/
            echo "Upload latest docker-compose file for dev env"
            curl \
            -H 'Authorization: token ${{env.GH_OAUTH_TOKEN}}' \
            -H 'Accept: application/vnd.github.v3.raw' \
            -O \
            -L 'https://${{env.GH_API_DOMAIN}}/repos/rutaks/ce-attendance-ms-api/contents/docker-compose/dev.docker-compose.yml?ref=dev' >> docker-compose/dev.docker-compose.yml
            echo "Loading latest app image from docker registry"
            mkdir -p dev-env
            cp ./docker-compose/dev.docker-compose.yml ./dev-env/dev.docker-compose.yml
            cd ./dev-env
            echo ${{env.ENV_VARS}} > .env
            docker login -u="${{env.DOCKER_USERNAME}}" -p="${{env.DOCKER_PASSWORD}}"
            docker pull ${{env.APP_REGISTRY_NAME}}:dev
            docker-compose -f dev.docker-compose.yml down -v
            docker-compose --env-file .env -f dev.docker-compose.yml up -d
